Repository AY2223S1-CS2113-W13-2/tp, pull requests merged in 2022-11, with the labels that each got.

#206 Major change to UserStorage and UserStorageParser
  data/timetable_info.txt
  data/uni_info.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/UserStorageParser.java
  src/main/java/seedu/duke/timetable/TimetableManager.java
  src/main/java/seedu/duke/user/UserUniversityListManager.java
  src/main/java/seedu/duke/userstorage/UserStorage.java
  src/test/java/seedu/duke/userstorage/UserStorageTest.java
  src/test/java/seedu/duke/userstorage/UserTimetableStorageTest.java
  src/test/java/seedu/duke/userstorage/UserUniStorageTest.java
Labels: priority.High, severity.Low

#247 Update ongzhihong's PPP
  docs/team/ongzhihong.md
Labels: type.Task, priority.Medium

#248 Fix bug when user deletes data directory
  src/main/java/seedu/duke/userstorage/UserStorage.java
Labels: type.Bug

#249 Update Sequence Diagrams for Commands
  docs/diagrams/AddCommand_Sequence.puml
  docs/diagrams/CreateCommand_Sequence.puml
  docs/diagrams/DeleteCommand_Sequence.puml
  docs/diagrams/ExitCommand_Sequence.puml
  docs/diagrams/FavouriteCommand_Sequence.puml
  docs/diagrams/HelpCommand_Sequence.puml
  docs/diagrams/ListCommand_Sequence.puml
  docs/diagrams/UserModuleMapping_Sequence.puml
  docs/diagrams/ViewCommand_Sequence.puml
  docs/images/AddCommand_Sequence.png
  docs/images/CreateCommand_Sequence.png
  docs/images/DeleteCommand_Sequence.png
  docs/images/ExitCommand_Sequence.png
  docs/images/FavouriteCommand_Sequence.png
  docs/images/HelpCommand_Sequence.png
  docs/images/ListCommand_Sequence.png
  docs/images/UserModuleMapping_Sequence.png
  docs/images/ViewCommand_Sequence.png
Labels: type.Task, priority.Medium

#250 Update ongzhihong's PPP
  docs/team/ongzhihong.md
Labels: type.Task, priority.Medium
