Repository AY2223S1-CS2113-W13-2/tp, pull requests merged in 2022-10, with the labels that each got.

#73 Add parsing for Favourite command and update Ui for better user help
  .github/workflows/gradle.yml
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandType.java
  src/main/java/seedu/duke/command/FavouriteCommand.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#86 Major Refactor to CommandParser
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ui/UiTest.java
Labels: priority.Medium

#87 Major Refactor to UserStorageParser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/UserStorageParser.java
  src/main/java/seedu/duke/user/UserUniversityListManager.java
  src/main/java/seedu/duke/userstorage/UserStorageParser.java
  src/test/java/seedu/duke/userstorage/UserStorageTest.java
Labels: type.Task

#94 Update CommandParser to reflect new Commands
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/test/java/seedu/duke/parser/CommandParserTest.java
Labels: priority.High

#99 Add and update JUnit tests for User Storage
  src/main/java/seedu/duke/parser/UserStorageParser.java
  src/main/java/seedu/duke/userstorage/UserStorage.java
  src/test/java/seedu/duke/userstorage/UserTimetableStorageTest.java
  src/test/java/seedu/duke/userstorage/UserUniStorageTest.java
Labels: type.Task, priority.Medium

#100 Add JavaDoc to CommandParser
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: priority.Medium

#101 Refactor Duke logic by creating methods to execute commands
  src/main/java/seedu/duke/Duke.java
Labels: type.Task

#109 Fix Command sequence diagrams for DeveloperGuide
  data/myinfo.txt
  docs/DeveloperGuide.md
  docs/diagrams/AddCommand_Sequence.puml
  docs/diagrams/CreateCommand_Sequence.puml
  docs/diagrams/DeleteCommand_Sequence.puml
  docs/diagrams/ExitCommand_Sequence.puml
  docs/diagrams/FavouriteCommand_Sequence.puml
  docs/diagrams/HelpCommand_Sequence.puml
  docs/diagrams/ListCommand_Sequence.puml
  docs/images/AddCommand_Sequence.png
  docs/images/CreateCommand_Sequence.png
  docs/images/DeleteCommand_Sequence.png
  docs/images/ExitCommand_Sequence.png
  docs/images/FavouriteCommand_Sequence.png
  docs/images/ListCommand_Sequence.png
  src/main/java/seedu/duke/parser/CommandParser.java
Labels: type.Task

#111 Update UserStorageParser to store module comments
  data/duke.txt
  data/myinfo.txt
  src/main/java/seedu/duke/parser/UserStorageParser.java
  src/test/java/seedu/duke/userstorage/UserUniStorageTest.java
Labels: type.Task, priority.Medium

#119 Bug fixes and logic flow improvements
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Database.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/user/UserModuleMappingList.java
  src/main/java/seedu/duke/user/UserUniversityListManager.java
  src/test/java/seedu/duke/command/DatabaseTest.java
Labels: priority.High, severity.High

#171 Handle exceptions for invalid university and module in database
  src/main/java/seedu/duke/command/Database.java
  src/main/java/seedu/duke/parser/UserStorageParser.java
  src/main/java/seedu/duke/user/UserUniversityListManager.java
  src/test/java/seedu/duke/userstorage/UserUniStorageTest.java
Labels: type.Bug

#172 Update User Guide and /help command output
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ui/UiTest.java
Labels: type.Task
